//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smarthis.UiPathLib.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smarthis.UiPathLib.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified a debug log will be produced in the specified file..
        /// </summary>
        public static string DebugLog_Description {
            get {
                return ResourceManager.GetString("DebugLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Log.
        /// </summary>
        public static string DebugLog_DisplayName {
            get {
                return ResourceManager.GetString("DebugLog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert a SecureString to a String.
        /// </summary>
        public static string SecureStringToString_Description {
            get {
                return ResourceManager.GetString("SecureStringToString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureString to String.
        /// </summary>
        public static string SecureStringToString_DisplayName {
            get {
                return ResourceManager.GetString("SecureStringToString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill with a SecureString variable.
        /// </summary>
        public static string SecureStringToString_SecuredString_Description {
            get {
                return ResourceManager.GetString("SecureStringToString_SecuredString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureString to be converted.
        /// </summary>
        public static string SecureStringToString_SecuredString_DisplayName {
            get {
                return ResourceManager.GetString("SecureStringToString_SecuredString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill with a String variable.
        /// </summary>
        public static string SecureStringToString_UnsecuredString_Description {
            get {
                return ResourceManager.GetString("SecureStringToString_UnsecuredString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted String.
        /// </summary>
        public static string SecureStringToString_UnsecuredString_DisplayName {
            get {
                return ResourceManager.GetString("SecureStringToString_UnsecuredString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://captcha-solver.hub.smarthis.com.br.
        /// </summary>
        public static string SolveCaptcha_BaseApiUrl {
            get {
                return ResourceManager.GetString("SolveCaptcha_BaseApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://keycloak.hub.smarthis.com.br.
        /// </summary>
        public static string SolveCaptcha_BaseAuthUrl {
            get {
                return ResourceManager.GetString("SolveCaptcha_BaseAuthUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique identifier key of the captcha container.
        /// </summary>
        public static string SolveCaptcha_CaptchaKey_Description {
            get {
                return ResourceManager.GetString("SolveCaptcha_CaptchaKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha Key.
        /// </summary>
        public static string SolveCaptcha_CaptchaKey_DisplayName {
            get {
                return ResourceManager.GetString("SolveCaptcha_CaptchaKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of captcha to be solved.
        /// </summary>
        public static string SolveCaptcha_CaptchaType_Description {
            get {
                return ResourceManager.GetString("SolveCaptcha_CaptchaType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha Type.
        /// </summary>
        public static string SolveCaptcha_CaptchaType_DisplayName {
            get {
                return ResourceManager.GetString("SolveCaptcha_CaptchaType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to captcha-solver.
        /// </summary>
        public static string SolveCaptcha_ClientId {
            get {
                return ResourceManager.GetString("SolveCaptcha_ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve Captchas, reCaptchas and hCatpchas.
        /// </summary>
        public static string SolveCaptcha_Description {
            get {
                return ResourceManager.GetString("SolveCaptcha_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve Captcha.
        /// </summary>
        public static string SolveCaptcha_DisplayName {
            get {
                return ResourceManager.GetString("SolveCaptcha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string SolveCaptcha_GrantType {
            get {
                return ResourceManager.GetString("SolveCaptcha_GrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hcaptcha.
        /// </summary>
        public static string SolveCaptcha_HCaptcha_DisplayName {
            get {
                return ResourceManager.GetString("SolveCaptcha_HCaptcha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;/api/v1/hcaptcha&quot;.
        /// </summary>
        public static string SolveCaptcha_HCaptcha_Endpoint {
            get {
                return ResourceManager.GetString("SolveCaptcha_HCaptcha_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url where the captcha image is hosted.
        /// </summary>
        public static string SolveCaptcha_ImageUrl_Description {
            get {
                return ResourceManager.GetString("SolveCaptcha_ImageUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Url.
        /// </summary>
        public static string SolveCaptcha_ImageUrl_DisplayName {
            get {
                return ResourceManager.GetString("SolveCaptcha_ImageUrl_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for password.
        /// </summary>
        public static string SolveCaptcha_Password_Description {
            get {
                return ResourceManager.GetString("SolveCaptcha_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SolveCaptcha_Password_DisplayName {
            get {
                return ResourceManager.GetString("SolveCaptcha_Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReCaptcha .
        /// </summary>
        public static string SolveCaptcha_ReCaptcha_DisplayName {
            get {
                return ResourceManager.GetString("SolveCaptcha_ReCaptcha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SolveCaptcha_ReCaptcha_Endpoint {
            get {
                return ResourceManager.GetString("SolveCaptcha_ReCaptcha_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token with the code that identifies the resolution.
        /// </summary>
        public static string SolveCaptcha_ResolutionToken_Description {
            get {
                return ResourceManager.GetString("SolveCaptcha_ResolutionToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution Token.
        /// </summary>
        public static string SolveCaptcha_ResolutionToken_DisplayName {
            get {
                return ResourceManager.GetString("SolveCaptcha_ResolutionToken_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill with the url where the captcha is located.
        /// </summary>
        public static string SolveCaptcha_SiteUrl_Description {
            get {
                return ResourceManager.GetString("SolveCaptcha_SiteUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Url.
        /// </summary>
        public static string SolveCaptcha_SiteUrl_DisplayName {
            get {
                return ResourceManager.GetString("SolveCaptcha_SiteUrl_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextCaptcha.
        /// </summary>
        public static string SolveCaptcha_TextCaptcha_DisplayName {
            get {
                return ResourceManager.GetString("SolveCaptcha_TextCaptcha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SolveCaptcha_TextCaptcha_Endpoint {
            get {
                return ResourceManager.GetString("SolveCaptcha_TextCaptcha_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for username.
        /// </summary>
        public static string SolveCaptcha_Username_Description {
            get {
                return ResourceManager.GetString("SolveCaptcha_Username_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SolveCaptcha_Username_DisplayName {
            get {
                return ResourceManager.GetString("SolveCaptcha_Username_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert a String to a SecureString.
        /// </summary>
        public static string StringToSecureString_Description {
            get {
                return ResourceManager.GetString("StringToSecureString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to SecureString.
        /// </summary>
        public static string StringToSecureString_DisplayName {
            get {
                return ResourceManager.GetString("StringToSecureString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill with a SecureString variable..
        /// </summary>
        public static string StringToSecureString_SecuredString_Description {
            get {
                return ResourceManager.GetString("StringToSecureString_SecuredString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted SecureString.
        /// </summary>
        public static string StringToSecureString_SecuredString_DisplayName {
            get {
                return ResourceManager.GetString("StringToSecureString_SecuredString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill with a String variable.
        /// </summary>
        public static string StringToSecureString_UnsecuredString_Description {
            get {
                return ResourceManager.GetString("StringToSecureString_UnsecuredString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to be converted.
        /// </summary>
        public static string StringToSecureString_UnsecuredString_DisplayName {
            get {
                return ResourceManager.GetString("StringToSecureString_UnsecuredString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amout of time (in seconds) to wait for the operation to be performed before generating an error.
        ///The default value is 30 seconds..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout reached..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
